import {Outfit} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import Head from "next/head";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";

const outfit = Outfit({ subsets: ["latin"],weight:["400","500","600","700"] });

 const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
 });
 const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
 });

export const metadata = {
  title: "Blog App",
  image:"/favicon.ico",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      
        <link rel="icon" href="/favicon.ico" />
        
        </Head>
      <body
         //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         className={outfit.className}
      >
        <ToastContainer theme="dark"/>
      
        {children}
        <Footer/>
      </body>
    </html>
  );
}
